name: Static Analysis
on: [push, pull_request]

env:
    PHP_EXTENSIONS: mbstring, fileinfo

jobs:
    phpstan:
        name: Run PHPStan analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.3

            - name: Configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
                  extensions: $PHP_EXTENSIONS
                  coverage: none

            - name: Restore Composer dependencies
              id: cache-php
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ matrix.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              if: steps.cache-php.outputs.cache-hit != 'true'
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest
                  composer-options: "--prefer-dist"

            - name: Run PHPStan analysis
              run: composer analyse
